### ISSUE TITLE
Admin login error

### ISSUE THREAD

**Issue by myspulin** [JuanLuisGarciaBorrego/jedy#1]
Hello,

I have tried to install Jedy cms and cannot access admin part, frontend is ok. When I submitted login form I got "500 Internal Server Error". When I checked the log file, there is error message:

request.CRITICAL: Uncaught PHP Exception LogicException: "The controller must return a response (null given). Did you forget to add a return statement somewhere in your controller?" at jedy\var\bootstrap.php.cache line 2986 {"exception":"[object](LogicException%28code: 0%29: The controller must return a response %28null given%29. Did you forget to add a return statement somewhere in your controller? at jedy\var\bootstrap.php.cache:2986)"} []

Could you please give me some hint how to fix this issue? Thanks for your help.

Best regards Lukas

**Comment by JuanLuisGarciaBorrego** [comment]
Hello @myspulin ,
I'll review it and inform you.

Thanks!

**Comment by JuanLuisGarciaBorrego** [comment]
Hi @myspulin 
I tried it and it works, however, I upgraded to a higher version of symfony. Remove vendor directory and make a pull repository
I hope to answer.
Thank you

**Comment by myspulin** [comment]
Hi @JuanLuisGarciaBorrego 
I tried to completly reinstall the app but the problem persist, still get the same error. I use windows system, I presume you have some linux, right?
